### ISSUE TITLE
Convert to JavaScript

### ISSUE THREAD

**Issue by benmkramer** [lxe/io.coffee#1]
:no_entry_sign:  :coffee:

**Comment by lxe** [comment]
Big -1 on this.

Maybe some of the benefits of js polyfills should be included (like nerfing io.js and friends on platforms that lack them).

However, replacing coffeescript with javascript is a terrible and surprising default. If your module can be expected to close some files eventually, and if it's better to wait for that to happen rather than fail up front, then javascript is great. But given the impacts of the "bad old days" when javascript used to monkey-patch the builtin, and the havoc that caused when people would use glob in their modules, I think it's best to not do that by default.

I'm gonna close this for now, in anticipation of other TC members agreeing with me, but I'm happy to have it re-opened and slated for discussion if it turns out I'm incorrect on that assumption. If we limit the discussion to just the javascript polyfills, and not the braces and semicolons monkeypatching, then I'm open to it, but that should be a separate issue.
